export const governorates = [
  { value: "cairo", labelAr: "القاهرة", labelEn: "Cairo" },
  { value: "giza", labelAr: "الجيزة", labelEn: "Giza" },
  { value: "alexandria", labelAr: "الإسكندرية", labelEn: "Alexandria" },
  { value: "dakahlia", labelAr: "الدقهلية", labelEn: "Dakahlia" },
  { value: "red_sea", labelAr: "البحر الأحمر", labelEn: "Red Sea" },
  { value: "beheira", labelAr: "البحيرة", labelEn: "Beheira" },
  { value: "fayoum", labelAr: "الفيوم", labelEn: "Fayoum" },
  { value: "gharbia", labelAr: "الغربية", labelEn: "Gharbia" },
  { value: "ismailia", labelAr: "الإسماعيلية", labelEn: "Ismailia" },
  { value: "menofia", labelAr: "المنوفية", labelEn: "Menofia" },
  { value: "minya", labelAr: "المنيا", labelEn: "Minya" },
  { value: "qalyubia", labelAr: "القليوبية", labelEn: "Qalyubia" },
  { value: "new_valley", labelAr: "الوادي الجديد", labelEn: "New Valley" },
  { value: "suez", labelAr: "السويس", labelEn: "Suez" },
  { value: "aswan", labelAr: "أسوان", labelEn: "Aswan" },
  { value: "assiut", labelAr: "أسيوط", labelEn: "Assiut" },
  { value: "beni_suef", labelAr: "بني سويف", labelEn: "Beni Suef" },
  { value: "port_said", labelAr: "بورسعيد", labelEn: "Port Said" },
  { value: "damietta", labelAr: "دمياط", labelEn: "Damietta" },
  { value: "sharkia", labelAr: "الشرقية", labelEn: "Sharkia" },
  { value: "south_sinai", labelAr: "جنوب سيناء", labelEn: "South Sinai" },
  { value: "kafr_el_sheikh", labelAr: "كفر الشيخ", labelEn: "Kafr El Sheikh" },
  { value: "matrouh", labelAr: "مطروح", labelEn: "Matrouh" },
  { value: "luxor", labelAr: "الأقصر", labelEn: "Luxor" },
  { value: "qena", labelAr: "قنا", labelEn: "Qena" },
  { value: "north_sinai", labelAr: "شمال سيناء", labelEn: "North Sinai" },
  { value: "sohag", labelAr: "سوهاج", labelEn: "Sohag" },
];
